version: '3.8'

services:
  frontend:
    build: ./desafiomv-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./desafiomv-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://turntable.proxy.rlwy.net:22409/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gCwBSXAUmgsWwwVFRSJzeStOpOwaDjha

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
